### ISSUE TITLE
A more explicit find function

### ISSUE THREAD

**Issue by KSXGitHub** [iter-tools/iter-tools#104]
Right now, `find()` returns `null` when item is not found, this doesn't help when one wants to find `null` itself, consider this:

```javascript
const res = find(
  x => x === null || x === undefined,
  iterable
)
```

In the above example, if `res` is `null`, it is impossible to know whether `iterable` has `null` or `iterable` just has no elements that satisfy the finding condition.

## Proposal

```typescript
function explicitFind<T> (
  func: (item: T) => boolean,
  iterable: Iterable<T>
): { found: true, value: T } | { found: false }
```

This function always return an object:
  * Property `.found` is a boolean.
  * Property `.value` is found value, only exist when `.found` is `true`.

## Note

* If there's a name better than `explicitFind`, let me know.

**Comment by sithmel** [comment]
You are exposing a flaw in the "find" function. But I am not sure that adding a slightly different "find" is the best solution.
I would rather keep the flawed but simpler "find" that works fine 99% of the times, and let the user figure out by themselves how to deal with the rare case (a very simple for loop).
