### ISSUE TITLE
Suggestion: Use tests as type tests

### ISSUE THREAD

**Issue by conartist6** [iter-tools/iter-tools#141]
So since this project was started, babel has released babel-plugin-typescript, which enables a new workflow for type testing which I think iter-tools should consider adopting. Basically babel can now strip typescript types, which means that jest can run typescript code without any further fuss. That means that the ideal thing to do is to simply make the jest tests typescript files and check them (separately) with the typescript compiler. Instead of having to try to figure out appropriate type assertions, this method allows you to be sure that whatever usages you tested will not have type errors.

Sequins actually goes a step further -- it's tests are polyglot type tests, using only syntax that is common to both TS and Flow. I guess I'm just making the point that it's good to know that we're not blocking ourselves from adding flow types, which I should do as well.

Anyway if there are no objections from @KSXGitHub  I'll set this up.

**Comment by KSXGitHub** [comment]
@conartist6 There's also [ts-jest](https://github.com/kulshekhar/ts-jest) (choose whatever you think is best).

However, `__spec__/*.ts` is still necessary, as jest only concern with whether the functions run correctly, not whether the functions can infer return type correctly.

**Comment by conartist6** [comment]
@KSXGitHub Actually that's not the case. Obviously the execution of the tests in jest won't check types, but the test framework has its own type defs which will check that the types resulting from an `expect()` call are assignable to anything put in `.toBe()` or `.toEqual()`. Running tsc on a test file will can still report usage errors, which is great because your test cases should already contain what you expect will be the common usage patterns and corner cases.

**Comment by sithmel** [comment]
I have no objections

**Comment by KSXGitHub** [comment]
Well, I would like each unit test to concern with only one aspect of a function. Making a test mange both types and runtime would lead to test writer forget about types. I'd like to keep type testing explicit.

**Comment by conartist6** [comment]
By the way, I'm going to be doing this in connection with #237

**Comment by conartist6** [comment]
Done.
