### ISSUE TITLE
Merge issues

### ISSUE THREAD

**Issue by conartist6** [iter-tools/iter-tools#169]
We should have a lint rule to prevent this kind of breakage, but we don't. It is not safe in this library to use named exports in any file with a default export, because we use a babel plugin which transforms files with only default exports to `module.exports = exports.default`. When we export multiple functions from `merge.js`, this code is breaking.

**Comment by sithmel** [comment]
As described above there are issues importing merge from node

**Comment by sithmel** [comment]
I am writing here the outcome of the discussion on https://github.com/sithmel/iter-tools/pull/174

There will be different "merge" functions:
* collate/asyncCollate (merge by order)
* interleave/asyncInterleave (merge by position)
* asyncInterleaveReady (merge by readiness)

There will also be a low level implementation. See this PR as a reference: https://github.com/sithmel/iter-tools/pull/174

@conartist6 is working on a PR

**Comment by conartist6** [comment]
This is fixed by the removal of `merge` in 7.x. The final advice on replacements to use is:
- `collate`/`asyncCollate` (merge by order or position)
- `asyncInterleaveReady` (merge by readiness)
- `interleave` (custom merges, including random ones)
