### ISSUE TITLE
investigate memory profiling

### ISSUE THREAD

**Issue by sithmel** [iter-tools/iter-tools#177]
https://github.com/sithmel/iter-tools/pull/174#issuecomment-459516419

**Comment by conartist6** [comment]
So I started my investigation into iter-tools perf characteristics. Running an iterator for an extended period certainly does cause memory allocations — they’re not optimized away via inlining.

The good news is that I now understand what mechanic of javascript engines makes running iterators efficient: [generational incremental garbage collection](https://v8.dev/blog/trash-talk#generational-layout). This is chrome’s information on it, but SpiderMonkey does something similar.

The upshot is that the kind of memory usage pattern involving very short-lived objects does not contribute at all towards a need to run the non-incremental garbage collector, which is the real bear as it has a tendency to stop execution of your code for a noticeable period of time — on the frontend probably enough to drop animation frames if you are displaying moving content.

Here’s what the incremental collection looked like in d8 as I ran through 50 million iterators of two map calls chained to a range function. The complete run took 6 seconds, by the way.  I’ve elided some debugging data that was irrelevant from the console output. 
```
57 ms: Scavenge 1.4 (2.3) -> 0.5 (3.3) MB, 1.1ms, allocation failure 
62 ms: Scavenge 1.4 (3.3) -> 0.5 (3.5) MB, 0.2ms, allocation failure 
66 ms: Scavenge 1.5 (3.5) -> 0.5 (3.5) MB, 0.1ms, allocation failure 
67 ms: Scavenge 1.5 (3.5) -> 0.5 (3.5) MB, 0.1ms, allocation failure 
68 ms: Scavenge 1.5 (3.5) -> 0.5 (3.5) MB, 0.1ms, allocation failure 
69 ms: Scavenge 1.5 (3.5) -> 0.5 (3.5) MB, 0.1ms, allocation failure 
70 ms: Scavenge 1.5 (3.5) -> 0.5 (3.5) MB, 0.1ms, allocation failure 
71 ms: Scavenge 1.5 (3.5) -> 0.5 (3.5) MB, 0.1ms, allocation failure 
72 ms: Scavenge 1.5 (3.5) -> 0.5 (3.5) MB, 0.1ms, allocation failure 
73 ms: Scavenge 1.5 (3.5) -> 0.5 (3.5) MB, 0.1ms, allocation failure 
```

What you are seeing is that once execution is in a steady state, it spends about 1/10th of its time collecting garbage. However that never halts its execution for more than a 1/10th of one millisecond, and it never leads to usage of more than 3.5MB of memory, which I believe is the space reserved for the youngest generations of objects.
