### ISSUE TITLE
Discussion: how many async methods should offer parallelism?

### ISSUE THREAD

**Issue by conartist6** [iter-tools/iter-tools#224]
Currently map and filter offer parallelism, however there are several other functions for which that optimization would be relevant. It is relevant when there are serial awaited calls to async functions mixed in with consuming an async iterable. Other [async] methods that meet this criteria are:
* some
* every
* takeWhile
* dropWhile
* find
* groupBy
* partition
* multiPartition
* reduce
* tap

There are several things to consider before we forge ahead here. How hard will it be to adapt our ParallelMapper code to adapt to early termination? Is it OK to overconsume the source? (For example a parallel find might get the first 5 items only to discover that the first item matches the predicate.)  Are there perf reasons not to make code use the ParallelMapper if it has concurrency 1? Certainly page weight would be one such concern, the only solution to which would be to create new and separate functions like `asyncMapParallel`. As a note that would not be a breaking change, since we have not yet released any functions with parallel implementations.

**Comment by sithmel** [comment]
We have a function that consume the iterable eagerly. And it is asyncBuffer.

The intention with map, filter and flatMap, was allowing to run their function argument in parallel.

For example:
```js
const superagent = require('superagent')

asyncMap((n) => {
  superagent
  .get(`/items/${n}`)
}, range(10))
```

**Comment by conartist6** [comment]
Right. Hence the list of functions that can run an async function argument, and would potentially benefit from doing it in parallel.

**Comment by sithmel** [comment]
@conartist6 yes.

Although, now that I see that with fresh eyes, I wonder if the numeric parameter was a mistake.

Perhaps we should have just implemented asyncMap like a chain of promises, like the ParallelMapper simplified. And use asyncThrottle to limit the parallelism.

**Comment by conartist6** [comment]
After everything we put into it the first time, I'm relatively certain there's no simpler way to rewrite asyncMap. And anyway a chain of promises is exactly what ParallelMapper is!

**Comment by sithmel** [comment]
Indeed, I meant ParallelMapper without number.

But your point stand still. I think all these methods can benefit of parallelization

**Comment by sithmel** [comment]
Hang on, ignore what I wrote about "ParallelMapper without number". I am not sure it makes sense :man_facepalming: 

Let me double check

**Comment by sithmel** [comment]
Yes I confirm. What I said doesn't make sense.
So for me it is definitely a *yes*.

In another news, running the benchmarks, ParallelMapper is faster than it should be. I suspect the concurrency is off by one. I am investigating

**Comment by sithmel** [comment]
I have written this test case, to prove the issue.
```js
  it('maps concurrently (check how many)', async function () {
    let concurrency = 0
    const iter = asyncMap(10, async (item) => {
      concurrency += 1
      expect(concurrency).to.toEqual(10)
      await delay(20)
      concurrency -= 1
      return item * 2
    }, range(200))
    await asyncToArray(iter)
  })
```
I tried to figure out how to solve it, but didn't manage to, so far.

**Comment by conartist6** [comment]
I adapted your test slightly and it does what I'd expect:
```js
  it('maps concurrently (check how many)', async function () {
    let concurrency = 0

    const iter = asyncMap(3, async (item) => {
      concurrency++
      await delay(50)
      return concurrency--
    }, range(10))
    expect(await asyncToArray(iter)).toEqual([4, 4, 4, 4, 4, 4, 4, 3, 2, 1])
  })
```

**Comment by conartist6** [comment]
Your problem I think is that you asserted on concurrency *before* the await.

**Comment by conartist6** [comment]
Oh but I guess that is off by one isn't it. Wasn't paying attention to the input

**Comment by conartist6** [comment]
All you need to do to fix it is that ParallelMapper should make a buffer of size `concurrency - 1` instead of just `concurrency`. If concurrency is one, we don't ever buffer anything and the code always takes the buffer-is-full path, which makes sense.

**Comment by conartist6** [comment]
Oh but that breaks concurrency 1. I think it really does make sense to separate out a `asyncMapParallel`, where the default `asyncMap` will be intended for use with sync mappers. I think it's good for readability too, if someone who isn't familiar with the code sees `asyncMap(5, fn, iterable)` they aren't going to know what the `5` is for. If they see `asyncMapParallel(5, fn, iterable)` however I think they may guess that `5` controls the amount of parallelism.

**Comment by sithmel** [comment]
I favourable as a principle (about having async-map-parallel and async-map).

But I am scared that will lead to a proliferation of "-parallel" variations.

What if we set the buffer to concurrency - 1 AND use a variations of the "next" method that doesn't use the buffer ?

**Comment by conartist6** [comment]
Parallel versions would proliferate the the list of methods I pasted above, and I don't think that proliferation is so bad. For the readme table of contents we can roll them in with the normal method, eg:
```
map (async)(parallel-async)
filter (async)(parallel-async)
...
```

We wouldn't need any more typedefs than we already have, which is nice.

And with my work to generate sync/async from templates, there wouldn't be additional maintenance cost to the non-parallel async version -- it's implementation and tests would be shared with the sync implementation.

**Comment by sithmel** [comment]
Fine for me.

**Comment by sithmel** [comment]
Keeping it open, waiting the implementation of the other parallel methods.

@conartist6 I am happy to take care of them, if you hadn't already

**Comment by conartist6** [comment]
@sithmel That would be great. I think the hardest part is going to be documenting all the variants, but that might prove to be easier in a website than it is in this very static README.

**Comment by conartist6** [comment]
New answer: 1. `asyncBuffer`.  Just wrap it around anything one of these methods we've mentioned and voila, parallelism.

**Comment by conartist6** [comment]
OK this answer was wrong. `asyncBuffer` is useful, but the mechanics of async generators mean that each promise returned from a transformer will still be awaited as part of `yield` or `yield await`, so it won't be possible to parallelize to the extent that parallelization is possible. That is to say, if you have `async func(value) => Promise`, you'll always end up waiting for the result of the promise before you call `func()` again.

**Comment by conartist6** [comment]
Note that `asyncBuffer` does help in the scenario noted originally: "when there are serial awaited calls to async functions mixed in with consuming an async iterable". In this case buffering ensures that the next items in the source iterable are fetched even as the results of the async calls are being awaited.

Thus I think the new list of methods which could benefit are simply those which make async calls for each value in source, i.e. `tap`, `map`, `flatMap`, `filter`, `some`, `every`, `find`, `takeWhile`, `dropWhile`, and `splitGroups`.

But should every one of those have a parallel implementation?

**Comment by conartist6** [comment]
Pretty much everything parallel can be built on top of an implementation of `mapParallel`, and when I had parallel implementations that is more or less what i did. Here are the examples:
```js
const asyncTapParallel = (source, fn) => asyncMapParallel(source, async (value) => (await fn(value)), value  );
const asyncFlatMapParallel = (source, fn) => asyncFlat(asyncMapParallel(source, fn));
const asyncFilterParallel = (source, fn) => asyncFlatMapParallel(source, async (value) => await fn(value) ? [value] : []);
const asyncSomeParallel = (source, fn) => asyncSome(asyncMapParallel(source, fn));
const asyncEveryParallel = (source, fn) => asyncEvery(asyncMapParallel(source, fn));
const asyncFindParallel = (source, fn) => asyncFirst(asyncFilterParallel(source, fn));
```

The others (`takeWhile`, `dropWhile`, `splitGroups`) involve intermediate representations of the data, but are still relatively concise.
