### ISSUE TITLE
Flat typedef: type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by conartist6** [iter-tools/iter-tools#226]
Problem in `src/__spec__/flat.spec.ts`:
```ts
// flat(0, iterable)
assert<{
  'depth = 0': IterableIterator<0 | 1 | 2>
  // ...
}>({
  'depth = 0': iter.flat(0, [0, 1, 2] as [0, 1, 2]), // Type instantiation is excessively deep and possibly infinite
  // ...
})
```

@KSXGitHub says this is an underlying issue in typescript-tuple

**Comment by KSXGitHub** [comment]
The only way to fix it right now is to stop using `typescript-tuple` and just return `Iterable<any>`. I could put more effort into it and potentially fix the issue without regression but I'm afraid TypeScript will change again in the future.

**Comment by conartist6** [comment]
I don't understand why it only happens with 0 though.

**Comment by conartist6** [comment]
Oh **** it doesn't, it's just that the TSC compiler has actually given up trying to evaluate any more of the type.

**Comment by KSXGitHub** [comment]
We can still have a few overloads for a few values of `depth` (0, 1, 2).

**Comment by conartist6** [comment]
I think we should follow the lead of the official typescript defs:
https://github.com/microsoft/TypeScript/blob/d484163d0f8445aa7e1e7b944550922e99cf8305/lib/lib.es2019.array.d.ts#L45

I think any overload that has `shouldFlat` should return `Iterable<any>`.

The only tricky thing will be that we'll need even more duplication than we have to support our curried/uncurried versions.

**Comment by conartist6** [comment]
So I adapted the types from the builtin `Array.prototype.flat` function but I'm still not quite there yet.

Here's what I have so far: https://gist.github.com/conartist6/d6330f61506f0b5cc5a356066106315b

What I'm trying to figure out how to deal with is having the types not fail up when part of the iterable to be flattened is not as deep as the depth parameter.

**Comment by KSXGitHub** [comment]
For such a long list of overloads, I think we should generate it from a code.

**Comment by conartist6** [comment]
I've thought about that, but I'd need to get it working first.

**Comment by conartist6** [comment]
OK I got a def that works.

**Comment by conartist6** [comment]
Fixed in 7.x
