### ISSUE TITLE
Compare to IxJS

### ISSUE THREAD

**Issue by conartist6** [iter-tools/iter-tools#227]
Just noticed that ReactiveX is in the space with https://github.com/ReactiveX/IxJS. I don't know how I never noticed it before. It looks to me like they're the most fully featured package I've seen yet.

Let's figure out how we stack up.
What do we do that they don't?
What do they do that we don't?

Here's what I see so far:

They're the only other library I've come across with API parity for sync and async iterators. Their parity comes from copy paste though, which is to say our deduplication work is an advantage.

They are using their own class structure instead of generator functions, which probably will make their code a bit more performant though harder to read and maintain.

They have almost 7x more weekly npm downloads than we do at the moment. Benefits of being in the Rx ecosystem I guess.

They don't seem to be capable of tree shaking, they're asking people who just want a few functions to import each of them from its internal file (ouch...)

They do support object oriented chaining *and* do not require all methods to be on the chain, though I think their technique for achieving this is rather mediocre.

**Comment by KSXGitHub** [comment]
They do not transpile their code to es5. This will leads to performance improvement at the cost of backward compatibility (user can always force their transpiler to transpile the module though). [I used this link to see the files](https://www.yarnpkg.com/en/package/ix?files).

> They don't seem to be capable of tree shaking, they're asking people who just want a few functions to import each of them from its internal file (ouch...)

Yep, [their entry file](https://cdn.jsdelivr.net/npm/ix@2.5.3/Ix.node.d.ts) has side effect imports.

**Comment by sithmel** [comment]
It seems they didn't discover yet the issue around not closing iterables/asyncIterables https://github.com/ReactiveX/IxJS/blob/master/src/asynciterable/zip.ts (no "return" call here)

The chaining is very cool and convenient. But it implies that you need to include the gorilla and the rest of the jungle if you need a banana. This is perfectly fine on node of course.
I still think there is a space for a very cool library built on top of iter-tools, that implements chaining.

> They do not transpile their code to es5

I have the impression that they are pointing to use that on node, rather than the browser.

**Comment by conartist6** [comment]
They show an example of just getting the banana:

> Instead of bringing in the entire library for AsyncIterable, we can pick and choose which operators we want, for bundling concerns.
> 
> // ES
> import { AsyncIterableX as AsyncIterable } from 'ix/asynciterable';
> import 'ix/add/asynciterable-operators/map';
> 
> // CommonJS
> const AsyncIterable = require('ix/asynciterable').AsyncIterableX;
> require('ix/add/asynciterable-operators/map');
> 
> const results = AsyncIterable.of(1,2,3)
>   .map(x => x + '!!');

**Comment by conartist6** [comment]
I still think that's almost worse though. For one since they're purposely employing import side effects, no file which includes that is going to be tree-shakable.

**Comment by conartist6** [comment]
Oh by the way, we've passed ix in downloads already and I haven't even put out the rc-1 package.
