### ISSUE TITLE
Typescript types for slice doers not support currying

### ISSUE THREAD

**Issue by Pajn** [iter-tools/iter-tools#239]
The JS code seems to support it but the type definition does not have an override for it

**Comment by conartist6** [comment]
I'm going to put up a fix, but I should warn you that none of the curried types are correct at the moment. The proper values for the generics are lost. The fix for that issue is coming as soon as possible, but since it will be a breaking change it's going to have to go in the next major release.

**Comment by conartist6** [comment]
Released 6.2.5 with that fix for you. My first release as the primary maintainer for the library!

**Comment by sithmel** [comment]
Congrats @conartist6 !
