### ISSUE TITLE
Partition methods unsound on infinite iterables

### ISSUE THREAD

**Issue by conartist6** [iter-tools/iter-tools#254]
There are some methods which require arrays to work correctly. Sort is an obvious example. I am going to posit that `partition` and `multiPartition` are actually another.

We already know that methods which must operate on arrays are outside the scope of iter-tools. This is primarily because we mean to support all iterables, including infinite iterables, which cannot ever be cached in arrays. This, however, is not the only pitfall of infinite iterables. Another can be easily demonstrated here:

```js
const [winners, alsoRan] = partition(i => i < 3, range())
for (const winner of winners) {
   /* Oops, we created an infinite loop.
    * We will continue trying to pull from the infinite source iterable
    * looking for the next value less than three. There is none.
    */
}
```

Essentially this means that if you have an infinite iterable, the method will only work well if you are sure that one type of object will never cease appearing in the output.

Consider though the case of the async variants of these methods when they are simply run on large iterables. It would almost always be the case that it would be inappropriate to try to partition the iterables using these methods. Trying to consume any one side of the partition in its entirety would be no faster than consuming the whole source. If I were trying to write code that was responsive to an async iterable of alphas and betas, I'd do something like `const [alphas, betas] = partition(isAlpha, source)`. Then in order to avoid being blocked, I'd have to try to consume the `alphas` and `betas` iterables simultaneously, using something like `Promise.race` to determine which result was actually ready. Essentially at this point the coder would be working defeat the implementation of our method, which mostly has to do with caching items, a behavior that seems to actually be undesired the more I think about it.

I think most of the time the appropriate thing to do in the code is simply
```js
for await (const item of source) {
  if (isAlpha(item)) {
    // Whatever is supposed to happen for an alpha
  } else {
    // Whatever is supposed to happen to beta
  }
}
```

Can anyone imagine a situation in which it would be more suitable to use partition than to just write a loop like the one above?

**Comment by conartist6** [comment]
Partition isn’t the only method that can’t be run on infinite iterables either. `takeSorted` is another one. I don’t mind takeSorted as much because it still represents a clean interface the most efficient solution possible for a certain type of problem. I do think though that we need to set a configurable max size for these source iterables of these methods with a reasonable default. E.g. `takeSorted` would give up and assume an infinite iterable if it consumes 100k items in its for loop. Technically if we don’t implement that it’s a security vulnerability.

**Comment by conartist6** [comment]
Others that can’t run on infinite iterables: `some`, `every`, `reduce`, `find`, and `toArray`. Obviously we shouldn’t get rid of all these methods, but we should absolutely impose that configurable 100k size limit on their sources, and we should either tag them specially in the documentation or create a section of the docs particularly for them.

**Comment by conartist6** [comment]
@sithmel I’d like to hear what you think about this

**Comment by conartist6** [comment]
I’m looking at the spec for `Array.from` since it also theoretically could cause an infinite loop if passed an infinite iterable, but at very least that method would eventually blow up when it ran out of memory for the output, so it is technically bounded in some way. `some`, `every`, `reduce`, `find`, and `toArray` lack even that termination condition.

**Comment by sithmel** [comment]
Using an infinite iterable we can have basically 2 potential side effect:
- some method will just blow up (because of memory). toArray and takeSorted for example
- some other will run forever and never return

From a certain point of view, it should be up to the dev to ensure that this is not happening ("slice" would do the trick easily).

> Technically if we don’t implement that it’s a security vulnerability.

I am not sure you could define that as a security vulnerability. It would be like saying that you have to remove the while loop from the language because it can be leveraged to run a DOS.

**Comment by conartist6** [comment]
Yeah I admit that it’s a bit fuzzy from a security perspective. Usually you can trust code (because you wrote it) and you would expect not to (implicitly) trust data which is passed to you from the outside. Iterables are code as data, so how does it make sense to think of them? An infinite iterable can’t be serialized, so code which accepts network, file, or form inputs need not worry. And if you are ever running untrusted code, regardless of whether it is an iterable or a callback or whatever, you should take steps to ensure that its runtime is bounded anyway. I guess ultimately it’s not unreasonable to just let the programmer shoot themselves in the foot if that’s what they want to do.

**Comment by conartist6** [comment]
@sithmel @KSXGitHub I have removed the partition and multiPartition methods in my branch.

**Comment by conartist6** [comment]
The issue partition has over and beyond other similar methods like `groupBy` is that with `groupBy` as long as you consume the all the result iterables in order you can be assured that your code will not end up in an infinite loop. With `partition`, the same consumption strategy will sometimes result in an infinite loop, and sometimes not. In my mind this means that the appropriate thing to do is use lodash: `const [evens, odds] = _.partition([...iterable], isEven);`.
