### ISSUE TITLE
Reactive Programming with async iterators?

### ISSUE THREAD

**Issue by KSXGitHub** [iter-tools/iter-tools#271]
Is it possible to replace [RxJS](https://rxjs-dev.firebaseapp.com/api) with iter-tools and async-iterators? If it is, are you interested in bringing them to this codebase?

**Comment by conartist6** [comment]
I'm sure some usages could be replaced, and also that we can't and wouldn't want to support all usages. @KSXGitHub do you want to scan through their docs and figure out which things of theirs we don't have yet that make sense in our paradigm? It would be great to know also which features Rx has that we don't and won't support so that we could write an iter-tools vs. Rx guide to help people pick the thing that matches what they need.

**Comment by conartist6** [comment]
The biggest difference obviously is push based vs pull based, and IxJS represents their own vision of what parts of Rx make sense in a pull-only library. I'm continuing to watch Ix, and will probably be happy to support what they support in order to gain traction for this library.

**Comment by KSXGitHub** [comment]
We can add the following:
  * Create infinite async iterator: `fromEvent`, `interval`
  * Operators (that deal with both infinite and infinite async iterators):  `asyncPartition`, `bufferCount`, `bufferWhen`, `pairwise`, `scan`, etc.

Observables in RxJS can be reused multiple times, but we can use `asyncFork`.

**Comment by conartist6** [comment]
We also can reuse our iterables multiple times, just so long as the source can be reused. Here are my thoughts on the methods:

`partition` does not work on pull based collections. I know you had implemented it already, but it just isn't sound.
`pairwise` is just `cursor(2)`. Do you think the additional name would be useful?
`scan` looks good, I can add that.
`fromEvent` and `interval` I need a little longer to think about. Async iterables are kind of a mixture of push and pull based collections. Indeed they do have the necessary property of allowing the source to tell the sink when to consume, but I'm not sure their other properties are so suitable.

**Comment by conartist6** [comment]
Also `buffer` means something different in the current iter-tools than it does in Rx.

**Comment by conartist6** [comment]
My main thought is that async iterables are not a great tool from working with push-based sources, particularly events. The big drawback is that they're asynchronous, where push based event handling usually isn't and shouldn't be.
That means a couple things:
- It will be slow. You're not going to want to use this to handle high volume events.
- You lose your stack trace. Where before you could see the code that triggered an event higher up the stack, now you'll just see the Promise resolution ASAP scheduling event as the root of the stack. Of course async stack tracing is better than it was, but you still can't see the state of the code higher up the stack.
- There's no way to guarantee that you're done processing the previous event by the time the next event is triggered.
- There's no way to interact with the event handler itself, e.g. APIs like `stopPropagation`. It's already too late, propagation will have completed by the time you have a reference to the event object.

Also you're forced to use `asyncFork` if you want multiple call sites wish to be able to consume an event stream expressed as an async iterable, which is a clumsy tool with which to implement a basic publish/subscribe pattern.

I don't think async iterables are going to take over much of Rx's job, even if they sort of could for some simple usages.

**Comment by conartist6** [comment]
@KSXGitHub can I close this?

**Comment by KSXGitHub** [comment]
yes
