### ISSUE TITLE
Discussion: package format improvements

### ISSUE THREAD

**Issue by conartist6** [iter-tools/iter-tools#282]
I'm creating this to take the place of #173. There are still unresolved questions, but I most of the discussion there is outdated. One major part of why they're outdated is that node has shifted its module strategy again: https://medium.com/@nodejs/announcing-a-new-experimental-modules-1be8d2d6c2ff

What I'm currently planning is to make two major releases, `iter-tools@7.x`, and `iter-tools@8.x`. 7.x will include all the API changes that have been in progress in the existing package format. 8.x will be a breaking change to the package format, allowing us to move towards how we want to distribute our code going forwards.

For 8.x I plan to separate out an `iter-tools-es` which consists only of module sources. It may or may not transpile async generators (down to non-async generators, probably), but it certainly will not transpile anything else. This package will be recommended for anyone who needs to support older browsers, which they will do by transpiling their node_modules. `create-react-app` already does this, so a whole ecosystem of code can just switch to using this package and they'll get exactly as much transpilation as they need. In terms of technical details, I plan to bundle the library sources all together with rollup, and will set `package.type: module` so that node 12+ will also be able to consume this library.

For the main iter-tools package I plan to transpile down to es2015. I see no reason for the core package to be written for a language versions that don't even have iterators. People who need to support es5 will still have plenty of options, including using 7.x. The files will be commonjs, and it will still be possible to import individual methods from inside the library in service of consumers with serious parse-time perf concerns.

**Comment by hillin** [comment]
Hi, a quick question, does this mean I can use the es package if I'm using iter-tools with typescript (no matter what es version I'm targeting with TS), because TS does all the transpile jobs anyways?

**Comment by conartist6** [comment]
As far as I know only bundlers like webpack would ever even consider transpiling code from inside `node_modules`.

**Comment by hillin** [comment]
Thanks! I'm using Angular so webpack too, does this mean I'm safe with the ES package?

**Comment by conartist6** [comment]
No, not necessarily. Webpack is just a tool, and has endless configuration possibilities. I could not answer your question without doing due diligence in finding out how your environment is actually configured. May I suggest moving further disussion to https://gitter.im/iter-tools/community? I try to avoid having support discussions in my issues.
