### ISSUE TITLE
takeSorted does not accept async comparator

### ISSUE THREAD

**Issue by matthieu-fesselier** [iter-tools/iter-tools#286]
It seems that if I'm using an async comparator with `asyncTakeSorted`, elements are randomly sorted.
For example: 
```javascript
 // Promise comparator
  const array = asyncTakeSorted(
    3,
    (a, b) => {
      if (a > b) return new Promise(resolve => resolve(1))
      else if (a < b) return new Promise(resolve => resolve(-1))
      else return new Promise(resolve => resolve(0))
    },
    [
    new Promise(resolve => resolve(2)),
    new Promise(resolve => resolve(1)),
    new Promise(resolve => resolve(3))
    ]
  );
  for await (let res of array) console.log(res)
  // prints 2, 3, 1

  // Normal comparator
  const array = asyncTakeSorted(
    3,
    (a, b) => {
      if (a > b) return 1
      else if (a < b) return -1
      else return 0
    },
    [
    new Promise(resolve => resolve(2)),
    new Promise(resolve => resolve(1)),
    new Promise(resolve => resolve(3))
    ]
  );
  for await (let res of array) console.log(res)
 // prints 1, 2, 3
```
When the comparator is a promise, it returns the values in an apparent random order.
Is it the expected behavior?

**Comment by conartist6** [comment]
It has never been my intention to support async comparators. I suppose we could include a warning though if people do create one, just for the sake of clarity.

Could I ask what your use case for the async comparator is? In general I would suggest that if you need to do something async to each piece of data that you should do it in a `map` step and then you would use `takeSorted` on the result. This is going to ensure that the async thing you need to do is going to happen `n` times for `n` items, where an async comparator would need to do your async action `n log n` times for `n` items.

**Comment by matthieu-fesselier** [comment]
Ok I understand your point.

I currently work with `query-ldflex` (https://github.com/solid/query-ldflex) which allows to request datas in SOLID pods.
When I get an array of resources, I get an async iterator. Each resource of this iterator is a proxy which provide an async way to access its properties.

What I try to do is to sort this array of resources by one value of the resource. Which means doing something like this:
```javascript
asyncTakeSorted(
  10,
  (key) => {
    return async (a, b) => {
      if (await a[key] > await b[key]) return 1;
      else if (await a[key] < await b[key]) return -1;
      else return 0;
    }
  },
  resources);
```

Let me know if it's not clear :)

**Comment by conartist6** [comment]
Interesting. Always great to hear about the real world use cases people are putting iter-tools to.

Do you still think an async comparator is the best way to handle this? It only potentially makes sense if your proxy objects cache their properties after the first async fetch. But now that I know your use case, I can say that there's an additional factor which makes it not make sense, which is that `asyncTakeSorted` will always need to consume the entire async iterable in order to do its sorting. This is really going to limit the scalability of your design. What I think you really want is a way to specify a sort as you query your data. Is there some reason that that is not possible?

**Comment by conartist6** [comment]
I'm planning to close this as wontfix, as I it does not seem that your use case can be properly supported by iterables.

Let me know if this is not OK with you. I strongly recommend you find a way to get a sorted async iterable of results, then subsequently use something like `slice` or `batch` that can actually avoid doing unnecessary fetches.

**Comment by matthieu-fesselier** [comment]
Indeed, the proxy objets do cache the properties after the first async fetch.
But you're right, the sorting should be handled in the library at request time. It's not possible at the moment but it's definitely the best way to handle this :)
