### ISSUE TITLE
Async Generators and Sync Generators can potentially be unified

### ISSUE THREAD

**Issue by KSXGitHub** [iter-tools/iter-tools#291]
When I compile the following code with `--target es2017`:

```typescript
function * foo () {
    yield 0
    yield 1
    yield * 'abcdef' 
}

async function * afoo () {
    yield 0
    yield 1
    yield * 'abcdef' 
}
```

I get the following for `afoo`:

```javascript
function afoo() {
    return __asyncGenerator(this, arguments, function* afoo_1() {
        yield yield __await(0);
        yield yield __await(1);
        yield __await(yield* __asyncDelegator(__asyncValues('abcdef')));
    });
}
```

Now, if I replace `__await`, `__asyncDelegator` and `__asyncValues` with `id = x => x` and `__asyncGenerator` with `(_, args, fn) => fn(...args)`, then `afoo` will act exactly like `foo`.

[playground link](https://www.typescriptlang.org/play/?noEmitHelpers=true#code/GYVwdgxgLglg9mABAKkcOdEAoCUiDeAUIiYgJ4wCmANgCaIAMxpFN9AjMya3SogOQBDAEYRalYP0SEAvoUKCAzmUhpw0eElSD0mXAS7kqvJqSNtEnMz3qoho8ZOlygA)

**Comment by conartist6** [comment]
That's interesting, I had never thought of basing a runtime solution on the transpiler's strategy. It is actually relatively clean.

I don't think I'd want to do this though. I suspect that the sync methods would take a significant performance hit. I wouldn't mind a solution that causes the async methods to take a bit of perf hit, but I want to keep the sync methods as fast as one could reasonably expect them to be.
