### ISSUE TITLE
Some packages listed under "dependencies" should be "devDependecies"

### ISSUE THREAD

**Issue by KSXGitHub** [iter-tools/iter-tools#293]
* babel-plugin-macros
* babel-plugin-minify-dead-code-elimination
* minimist
* recursive-readdir
* sane

**Comment by KSXGitHub** [comment]
BTW, why don't you just publish your patched version of sane to npm to use in iter-tools? @conartist6

**Comment by conartist6** [comment]
Good catch

**Comment by KSXGitHub** [comment]
I have pattern of monorepo that separates production dependencies (used by the npm package) from development dependencies (used by the tools that we use to test/build/generate the npm package):
* I makes 3 folders: "packages", "test", and "tools".
* And I use pnpm (instead of npm) to link them all together.
That way, I will never mistakenly import a dev dependency in production code nor will I ever put dev dependency under production section.

If you're interested:
* https://github.com/nodejs-monorepo-templates/typescript-monorepo-esm is the template
* https://github.com/tsfun/tsfun, ksxnodeapps
/
fun-little-utilities, https://github.com/ksxnodeapps/make-mjs, and https://github.com/KSXGitHub/personal-packages are a few repos that use the pattern.

**Comment by conartist6** [comment]
This is the sort of thing you do that makes me nervous. It seems like you always have a different way of doing things. I don't see why I should avoid using devDependencies since they're meant to be used exactly the way I'm using them. If I don't look for a completely different solution to the problem, I can probably leverage other people's code for problems like detecting unused deps, or deps that should be devDeps.

**Comment by conartist6** [comment]
In this case for example I think [npm-check-unused](https://www.npmjs.com/package/npm-check-unused) should be sufficient to prevent this happening again.

**Comment by conartist6** [comment]
I'll add a `verify:dependencies` script here; I think you'll want to include that in your github actions jobs.

**Comment by KSXGitHub** [comment]
> This is the sort of thing you do that makes me nervous. It seems like you always have a different way of doing things.

I like call it "innovation" :)

>  don't see why I should avoid using devDependencies since they're meant to be used exactly the way I'm using them.

Does not mean you shouldn't look for new ways to solve a problem. And to be completely frank, npm had made poor design choices.

> I can probably leverage other people's code for problems like detecting unused deps, or deps that should be devDeps.

You totally can. You may find all import lines within the src directory and compare them to package.json.

**Comment by conartist6** [comment]
After rooting around a bit more it looks like `depcheck` is the real tool, all other packages are just built on top of it. It has at least one issue that affects us though: https://github.com/depcheck/depcheck/issues/421
