### ISSUE TITLE
Integrate with codecov.io

### ISSUE THREAD

**Issue by conartist6** [iter-tools/iter-tools#306]
The goal is to get coverage reports on every PR, to get coverage badges which update themselves and remove the old infrastructure for manually generating and displaying coverage badges, and finally to shore up areas of poor test coverage.

**Comment by JacobMGEvans** [comment]
I would be interested in being assigned to this and giving it a shot.

**Comment by conartist6** [comment]
Awesome! I'm here if you need any help or advice. Be sure to check out CONTRIBUTING.MD, and please if anything isn't clear enough how things should work, feel free to open a doc PR or let me know so that I can clarify.

**Comment by JacobMGEvans** [comment]
Is Travis currently installed and integrated?

**Comment by conartist6** [comment]
It is.

**Comment by JacobMGEvans** [comment]
Is there a public site for that Travis dashboard so I can see the logs and what not?

**Comment by conartist6** [comment]
Closed by #312
