### ISSUE TITLE
Flow types!

### ISSUE THREAD

**Issue by conartist6** [iter-tools/iter-tools#307]
I've designed the library with the intent that it will have typescript types as well as flow types. The basic infrastructure should all be in place to support flow types, I just haven't written them yet. The typescript types should serve as an excellent reference.

In order to support multiple kinds of typedefs, I have configured jest so that it actually uses the flow parser, though using any more than the syntax common to Typescript and Flow will break things. I do not run the type checkers on the test files directly. Instead they are copied to `.auto.spec.ts` files, which have the type checker run on them. I chose to make copies of these files with IDE support in mind, given that most IDEs will choose to run a type checker based on the file extension, and would not support two separate type checkers being run on the same file type.

So: what you should do is this:
- Set up a flowconfig and add flow as a devDependency
- Create a new file generator in `generate/generators`. You should crib most of it from `generate/generators/type-tests` which is currently responsible for generating those [auto.spec.ts](https://github.com/iter-tools/iter-tools/blob/master/generate/generators/type-tests/type-tests-generator.js#L38) files. You should generate `auto.spec.flow` files. You'll need to ensure that a `// @flow` comment is inserted into those generated test files.
- Read CONTRIBUTING.md for a description of `$` macro processing, then configure the types generator to work on `.js.flow` files. I would prefer this method of writing libdefs over a `flow-typed` folder.

Once you've done this you can start filling in flow typedef files alongside the existing `d.ts` files. You'll know you're done when you can run `flow` on those new generated tests and it reports no errors!

**Comment by conartist6** [comment]
If someone expresses interest in writing the actual flow typedefs, I could also be convinced to put up a partial PR with most of the boilerplate described above.

**Comment by conartist6** [comment]
I'm closing this. The info is outdated, and nobody has come asking me for flow types. Where I once wanted to avoid taking sides between TS and Flow, I now consider TS to have won out over Flow.

If anyone wants to use this in a flow project they can put defs into the flow-typed repo and I'm happy to review them.

**Comment by skeggse** [comment]
Yup the last place I know of that was using flow fairly recently made the switch over to TS. sgtm
