### ISSUE TITLE
How to build this tool into a single file for browser?

### ISSUE THREAD

**Issue by alexwenbj** [iter-tools/iter-tools#331]
I want to use this amazing tool for my web, but when I run `npm run build`,it built many files for me. My question is:how can I build a single (minified) file?Thank you.

**Comment by conartist6** [comment]
Hello.

I'd recommend using rollup for that. But even more than that I'd recommend using rollup or webpack to bundle all the code that you want to have on your page!

What are you hoping to end up with? I'm assuming you want a global variable called, say, `iterTools`. If so your rollup config might look like:
```
// rollup.config.js
module.exports = {
  input: ['/dist/index.js'],
  output: {
    format: 'iife',
    name: 'iterTools',
  }
};
```

If you have further questions about this, [gitter](https://gitter.im/iter-tools/community) is the place to ask them. I'll still get email notifications about anything you post there, and will be happy to help.
