### ISSUE TITLE
Why was tee removed?

### ISSUE THREAD

**Issue by alvaro-cuesta** [iter-tools/iter-tools#338]
So I came to this repo because I needed `asyncTee` and couldn't wrap my head around making my own one, only to realize [`tee` was removed today](https://github.com/iter-tools/iter-tools/blob/master/CHANGELOG.md#700-rc0---2019-12-13) (that's what I call good timing :P)

Why was it removed? Is there a better alternative? Was it problematic?

Please document this somewhere! (the CHANGELOG maybe?)

**EDIT:** I managed to find [this comment](https://github.com/iter-tools/iter-tools/issues/156#issuecomment-459635593). Is `fork` and improved `tee`? Is there any other difference between them? Couldn't find when in was added in the CHANGELOG, even though it's missing in the 6.x tag.

**Comment by alvaro-cuesta** [comment]
Actually, now that I'm reading 6.x's documentation, `tee` isn't what I need either.

> caching the values when one of the copy pull a new value from the original iterable

I don't really need the caching: I just want the input iteration to block as long as there's any output to be pulled. Is there anything in `iter-tools` that supports my use case?

I was expecting to mimic async channels. I'm trying to change a push-based API (channels) into a pull based one (iterators, which IMHO are easier to compose compared to channel's imperative API), and was hoping for an already existing solution to this use case (which is simpler in channels since it's just putting to the N channels).

**Comment by conartist6** [comment]
Well, it's still in the non-rc version of iter-tools. `tee` was replaced with `fork` which has a slightly different API but does more or less the same thing. I'll update the changelog to mention fork on the line that mentions the removal of `tee`.

**Comment by conartist6** [comment]
If I understand you're saying that you want asyncFork, except that there would be some max size to the fork buffer, and if the buffer filled up because some consumers were lagging behind then all consumers would be forced to wait. Do I understand correctly?

**Comment by conartist6** [comment]
You'll find some more of my thoughts on the topic of mixing push-based and pull-based techniques [here](https://github.com/iter-tools/iter-tools/issues/271).

**Comment by alvaro-cuesta** [comment]
> I'll update the changelog

Thanks!

> Do I understand correctly?

Yeah I think you do. I was hoping I could then use `asyncBuffer` to implement a buffered "channel".

I'm trying to get a better feeling for how channels and async iterators relate to each other. Are they isomorphic? What are their practical differences? Are there any meaningful differences apart from push vs pull API?

I feel like they're sides of the same coin, but I couldn't find any literature about their relationship and I was hoping I could write some real world examples on that.

So far channels have felt better at plumbing, like the use case I present (blocking fork).

**Comment by conartist6** [comment]
They're definitely sides of the same coin, the coin being the direction of control flow. So far I'm not convinced that there's a good way to convert something like an observable into an async iterable. It looks to me like IxJS will turn an async iterable into an observable (see [here](https://github.com/ReactiveX/IxJS/blob/master/src/Ix.ts#L225)), but doesn't offer the ability to convert the other way around. Of course it's always difficult to know what's in that library since they don't have any API documentation >_<.

I haven't used it myself, but I think you might be interested in [wonka](https://github.com/kitten/wonka). As I understand it offers a set of operations that is defined over both push and pull based streams.

**Comment by conartist6** [comment]
Also I dig your evil purple tentacle profile pic. Classy.

**Comment by conartist6** [comment]
I'm going to close this. If you come up with a concrete suggestion for an addition/improvement to the library make a new issue for it, but at the moment I don't think I intend to support the use case you're thinking of.

**Comment by conartist6** [comment]
I'm curious, did you figure out what the right solution to your problem was? If so, what was it?
