### ISSUE TITLE
Last or lastAsync doesn't seem to be available in 6.2.6

### ISSUE THREAD

**Issue by opr** [iter-tools/iter-tools#340]
I couldn't find anything in the docs telling me this to be the case but `import {takeWhile, last} from 'iter-tools/es2018';` on 6.2.6 fails - is it the case that this was just added in the 7.0.0 rc?

**Comment by conartist6** [comment]
`last` was added in `7.0.0-rc.0`. Please ask questions in [gitter](https://gitter.im/iter-tools/community). I get email notifications about what is posted there and you will get a response every bit as quickly.

**Comment by conartist6** [comment]
By the way I can't guarantee that there won't be any more breaking changes before `7.0.0` is out of the RC stage, but I'd wager that it's still better than `6.2.6`. Test coverage is through the roof in the 7x line.

**Comment by opr** [comment]
That's ok, I was just a little confused, forgive me if I'm wrong but I couldn't see anywhere in the API docs mentioning these were only available in 7.0.0-rc.0 - only in the changelog which I admittedly did not read, sorry. I might be in the minority here but I'd expect the documentation linked to from the readme in master to match the code available on the master branch, or what gets pulled from npm. I think it's slightly odd that the docs linked to are for 7.0.0-rc.0, but I admit I don't know if this is what other libraries do so it could be me being dumb for not knowing the protocol!

The only clue I got on the API docs was the URL and branch changing. I hope I'm not coming across as aggressive because I'm not trying to be I just wanted to explain why I got confused and made the issue. Thanks :)

**Comment by conartist6** [comment]
If you came to API.md from the npm site, then you must have been looking at the 7.0.0-rc.0 package there. It's the only released README that links to that file. So yes, if you access the docs through npm, you'll always see the docs for the version of the package you're looking at.

There was a period of about 1 - 2 minutes where I was messing around with the package tags and the rc release was showing under the `latest` tag. Maybe you loaded the npm page just then?

**Comment by opr** [comment]
I don't think it was just lucky timing. If you come to the Github page from the normal NPM page and click "Please read our API docs!" then it takes you to the docs for 7.0.0-rc.0 - that's what confused me

**Comment by conartist6** [comment]
Could you please send me the link to the page on npm?

**Comment by conartist6** [comment]
<img width="1068" alt="Screen Shot 2019-12-16 at 10 53 38 AM" src="https://user-images.githubusercontent.com/540777/70934279-6aa58300-1ff2-11ea-8ac1-c948a270cae7.png">

If it seems like I'm confused I am. The above is what I see. The readme for the 6x package with no link to API.md.

**Comment by opr** [comment]
https://www.npmjs.com/package/iter-tools yep this is what I see - so on the right-hand-side you can click through to the github page: https://github.com/sithmel/iter-tools - from here I can view the API docs link. 

I might be misunderstanding something, but I would expect the "master" (6.2.6) page on npm to link through to the "master" (6.2.6) page on github, which it does, however the readme on master links through to docs on 7.0.0-rc.0 - maybe I'm being really nitpicky here but it confused me enough to make an issue so perhaps other people are getting this confused too.

**Comment by opr** [comment]
![image](https://user-images.githubusercontent.com/5656702/70945429-14b1f900-204d-11ea-8c50-f5b6b015b5b7.png)
Maybe this confused me too

**Comment by conartist6** [comment]
Oh yeah I didn't consider that. I might be able to make it read a little better by having that shield link to the latest tag and then perhaps just tweaking the published readme not to have the npm shield at all since it's obviously not necessary on npm. In general though that's just what happens when you go to github: you see master. I don't think that's something for me to fix. Master will always be ahead of what's published, and thus cause you to see docs for unpublished code. That's hardly unique to this project.
