### ISSUE TITLE
Type definitions for pipe and compose are backwards

### ISSUE THREAD

**Issue by chuckwondo** [iter-tools/iter-tools#341]
In the 7.0.0 release candidate, the type definitions for `pipe` and `compose` are backwards. The definitions for `pipe` are what the definitions for `compose` should be, and vice-versa. (BTW, thank you for returning `pipe` to be simply `compose` in the reverse direction!)

**Comment by conartist6** [comment]
Oops, good catch. Will fix and put up a patch build. You are quite welcome for that, and thank you for trying out the RC!
