### ISSUE TITLE
publish .mjs versions of es2018/internal packages

### ISSUE THREAD

**Issue by skeggse** [iter-tools/iter-tools#352]
The es2015 and es5 subdirectories include `.mjs` versions of the internal packages, but the `es2018` version does not:

```
$ ls */internal/
es2015/internal/:
circular-buffer.js   clone-regexp.js   delay.js   ensure-async-iterable.js   ensure-iterable.js   math.js   querable-promise.js
circular-buffer.mjs  clone-regexp.mjs  delay.mjs  ensure-async-iterable.mjs  ensure-iterable.mjs  math.mjs  querable-promise.mjs

es2018/internal/:
circular-buffer.js  clone-regexp.js  delay.js  ensure-async-iterable.js  ensure-iterable.js  math.js  querable-promise.js

es5/internal/:
circular-buffer.js   clone-regexp.js   delay.js   ensure-async-iterable.js   ensure-iterable.js   math.js   querable-promise.js
circular-buffer.mjs  clone-regexp.mjs  delay.mjs  ensure-async-iterable.mjs  ensure-iterable.mjs  math.mjs  querable-promise.mjs
```

It'd be nice to be able to use `import`/`export` syntax for all these resolved modules.

Along these lines, it might also be a good idea to have `mjs` files import other `mjs` files with the explicit extension, in case the loading mechanism being used doesn't usually prefer `mjs` files except in the case of `iter-tools`. Thoughts?

**Comment by conartist6** [comment]
I believe that is fixed already in `iter-tools@next`. Despite being a prerelease it should be more stable than 6 due to the number of bugs I proactively found and fixed.

**Comment by skeggse** [comment]
Ah, good to know - thanks!

Any thoughts on

>Along these lines, it might also be a good idea to have `mjs` files import other `mjs` files with the explicit extension, in case the loading mechanism being used doesn't usually prefer `mjs` files except in the case of `iter-tools`.

**Comment by conartist6** [comment]
I am intending to do that, yes. This setup was made before node reworked their mechanism for es module loading. When converted to the newer specification it will be important that we do that. You can find quite a bit of discussion of the issue here: https://github.com/iter-tools/iter-tools/issues/292
