### ISSUE TITLE
7.x release date?

### ISSUE THREAD

**Issue by nomcopter** [iter-tools/iter-tools#368]
When will 7.x be stable? We use and like `iter-tools` but would like to avoid upgrading to a release candidate in production.

Our biggest issues with 6.x are lack of a few functions (`asyncFork, asyncSplitAt, asyncTakeSorted, asyncIsEmpty`) and `asyncFilter` performance. 

```ts
const n = 100000;
const evens = await iter.pipe(
  iter.range(n),
  iter.asyncFilter(async (n) => n % 2 == 0),
  iter.asyncToArray,
);
```

Takes 700ms on my machine, but takes a more reasonable 150ms with `v7.0.0-rc.0`. Replacing `asyncFilter` with 
```ts
function asyncFilter<T>(predicate: (t: T) => iter.MaybePromise<boolean>) {
  return async function* (iterable: iter.AsyncIterableLike<T>) {
    for await (const i of iterable) {
      if (await predicate(i)) {
        yield i;
      }
    }
  };
}
```
makes that function take ~40ms.

**Comment by conartist6** [comment]
It's going to be soon. I quit my job, in part because there was so much open source work I have planned and it seemed much more impactful than anything I was doing at work. But I'm also moving across the country. Currently I'm half way across, but the plan is to dig into iter-tools again when I've arrived.

Now that said, just use `7.0.0-rc.0`. It's easily more stable than `6.x`. I've done so much work on it including vastly expanding test coverage. I've tracked most of the bugs I discovered and fixed, but probably not even all of them. There's only two breaking changes I'm still planning to make -- I'm planning to rename `last` to `takeLast` since I am hopeful that reverse iteration will eventually be possible (and I feel O(1) and O(n) functions deserve different names). Also split functions that return strings when given string inputs will instead always return iterators. That work is not finished yet.

**Comment by nomcopter** [comment]
Thanks for the quick response! We'll go ahead and upgrade then. Can attest to the impact of this lib it's helped us a lot :)

**Comment by conartist6** [comment]
Ah, and finally it's no surprise that your own version is faster. iter-tools does validation on its inputs and has currying built in. I decided that completeness and correctness were more important than blazing speed, and the [currying and validation code](https://github.com/iter-tools/iter-tools/blob/master/src/internal/curry.mjs) is not insignificant in cost.

Given that cost, I keep "bare bones" versions of each method internally. They skip currying and validation, and I use them when I trust the call site, for example when one method calls another as part of its implementation. It might be worth thinking about exposing those, but they have slightly different signatures. In particular the iterable always comes first, since it is never optional and other arguments may be. Also bare bones variadic methods expect an iterable of iterables to come first, instead of the varargs style. I'll have to think more about the implications of exposing those. What would the naming scheme be for example? How would I deal with the types? But one of my guiding principles is that people shouldn't come to iter-tools and then realize they need either a second library, or to write a simpler implementation themselves. What do you think?

**Comment by conartist6** [comment]
Glad to hear it. I've put a lot of energy into it and I'm never sure how many people are really using it. I'm kind of keeping it in stealth mode a little until I'm happy enough to release 7.0

**Comment by nomcopter** [comment]
I know the feeling - I only really hear about usage of my open source projects when people are running into issues with it :P

As far as the different perf implications, I think a fixed overhead involved with making the functions safer and more consistent is definitely worth it. A 3x (let alone a 17x) performance hit that scales with input size makes it hard to choose this library. One of the main reasons we use `Iterable`/`AsyncIterable` over arrays in the first place is to try and help with performance (although mostly memory usually).

I don't think exporting different versions would solve anything, as then choosing which to use in the right situation can become nontrivial. Have you spent time attempting to optimize them? It is possible there may be some low hanging fruit that can make your proper implementations as fast as the naive ones.

**Comment by conartist6** [comment]
Yes. I did quite lot of optimization work as part of 7.x, as you can see. That said, a lot of it was done based on my knowledge of engine optimization techniques and without hard perf test numbers. The biggest change I made was to ensure that the currying and validation core has stable data types no matter which function it's processing inputs and outputs for. If I did the work right it will get hot fast and stay hot.

Our of curiosity which transpilation level are you using? Are you on node or browser? If possible you'd always get better perf by using less transpiled code.

**Comment by nomcopter** [comment]
Relevant tsconfig.json pieces:
```json
{
  "compilerOptions": {
    "downlevelIteration": true,
    "moduleResolution": "node",
    "module": "commonjs",
    "target": "es2019",
  }
}
```

Running on Node v12. Can get a profile for you next week if useful.

**Comment by conartist6** [comment]
Are you importing from `iter-tools/es2018`? That would be the biggest perf boost you could get.

**Comment by conartist6** [comment]
Also what I'm reading about `downlevelIteration` makes it seem like it would be pointless if your target was `es2019` running on node 12. Any particular reason you have that turned on?

**Comment by nomcopter** [comment]
`downlevelIteration` looks like cruft from when we on Node v8 - should be removable now. Ran some benchmarks on Node 12 - ES5 is shockingly slow!

```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "commonjs",
    "target": "es2019",
    "lib": [
      "DOM",
      "es2020"
    ],
  }
}
```

```ts
import * as iterEs5 from 'iter-tools/index.js';
import * as iterEs2015 from 'iter-tools/es2015';
import * as iterEs2018 from 'iter-tools/es2018';

const VERSIONS = {
  iterEs5,
  iterEs2015,
  iterEs2018
};

const COUNTS = [1, 1000, 1000000];

async function bench() {
  for (const [name, iter] of Object.entries(VERSIONS)) {
    for (const count of COUNTS) {
      const start = Date.now();
      const evens = await iter.asyncToArray(
        iter.asyncFilter(async (n: number) => n % 2 == 0,
          iter.range(count)))

      if (evens.length !== Math.ceil(count / 2)) {
        console.log(evens);
        throw new Error('oh no');
      }

      console.log(`${name} took ${Date.now() - start}ms to iterate ${count} times.`);
    }
  }
}

bench();
```

```
iterEs5 took 2ms to iterate 1 times.
iterEs5 took 15ms to iterate 1000 times.
iterEs5 took 1095ms to iterate 1000000 times.
iterEs2015 took 1ms to iterate 1 times.
iterEs2015 took 3ms to iterate 1000 times.
iterEs2015 took 1093ms to iterate 1000000 times.
iterEs2018 took 1ms to iterate 1 times.
iterEs2018 took 1ms to iterate 1000 times.
iterEs2018 took 466ms to iterate 1000000 times.
```

**Comment by nomcopter** [comment]
ES2018 seems comparable enough to native 👍 

```ts
import * as iterEs5 from 'iter-tools/index.js';
import * as iterEs2015 from 'iter-tools/es2015';
import * as iterEs2018 from 'iter-tools/es2018';

const nativeDirect = {
  async *range(amount: number) {
    for (let i = 0; i < amount; i++) {
      yield i;
    }
  },
  async *asyncFilter<T>(predicate: (t: T) => boolean | Promise<boolean>, iterable: AsyncIterable<T>) {
    for await (const i of iterable) {
      if (await predicate(i)) {
        yield i;
      }
    }
  },
  async asyncToArray<T>(iterable: AsyncIterable<T>) {
    const result = [];
    for await (const n of iterable) {
      result.push(n);
    }
    return result;
  }
} as any;

const VERSIONS = {
  iterEs5,
  iterEs2015,
  iterEs2018,
  nativeDirect,
};

const COUNTS = [1, 1000, 1000000];

async function bench() {
  for (const count of COUNTS) {
    for (const [name, iter] of Object.entries(VERSIONS)) {
      const start = process.hrtime();
      const evens = await iter.asyncToArray(
        iter.asyncFilter(async (n: number) => n % 2 == 0,
          iter.range(count)))

      if (evens.length !== Math.ceil(count / 2)) {
        console.log(evens);
        throw new Error('oh no');
      }

      const [s, ns] = process.hrtime(start);
      console.log(`${name.padEnd(12)} took ${(s * 1000 * 1000 * 1000 + ns).toString().padStart(10)}ns to iterate ${count} times.`);
    }
  }
}

bench();
```

```
iterEs5      took    1712475ns to iterate 1 times.
iterEs2015   took     658426ns to iterate 1 times.
iterEs2018   took     405663ns to iterate 1 times.
nativeDirect took      96373ns to iterate 1 times.
iterEs5      took   11807146ns to iterate 1000 times.
iterEs2015   took    4655179ns to iterate 1000 times.
iterEs2018   took    1011225ns to iterate 1000 times.
nativeDirect took     840363ns to iterate 1000 times.
iterEs5      took 1098091249ns to iterate 1000000 times.
iterEs2015   took 1093262454ns to iterate 1000000 times.
iterEs2018   took  471461027ns to iterate 1000000 times.
nativeDirect took  374463609ns to iterate 1000000 times.
```

**Comment by nomcopter** [comment]
Although sad how much native arrays beat native generators :o

```ts
import * as iterEs5 from 'iter-tools/index.js';
import * as iterEs2015 from 'iter-tools/es2015';
import * as iterEs2018 from 'iter-tools/es2018';

const nativeGen = {
  async *range(amount: number) {
    for (let i = 0; i < amount; i++) {
      yield i;
    }
  },
  async *asyncFilter<T>(predicate: (t: T) => boolean | Promise<boolean>, iterable: AsyncIterable<T>) {
    for await (const i of iterable) {
      if (await predicate(i)) {
        yield i;
      }
    }
  },
  async asyncToArray<T>(iterable: AsyncIterable<T>) {
    const result = [];
    for await (const n of iterable) {
      result.push(n);
    }
    return result;
  }
} as any;

const VERSIONS = {
  iterEs5,
  iterEs2015,
  iterEs2018,
  nativeGen,
};

const COUNTS = [1, 1000, 1000000];

async function bench() {
  for (const count of COUNTS) {
    for (const [name, iter] of Object.entries(VERSIONS)) {
      const start = process.hrtime();
      const evens = await iter.asyncToArray(
        iter.asyncFilter(async (n: number) => n % 2 == 0,
          iter.range(count)))

      if (evens.length !== Math.ceil(count / 2)) {
        console.log(evens);
        throw new Error('oh no');
      }

      const [s, ns] = process.hrtime(start);
      console.log(`${name.padEnd(12)} took ${(s * 1000 * 1000 * 1000 + ns).toLocaleString().padStart(13)}ns to iterate ${count} times.`);
    }
    const start = process.hrtime();
    const all = [];
    for (let i = 0; i < count; i++) {
      all.push(i);
    }
    const evens = [];
    for (let i = 0; i < all.length; i++) {
      if (all[i] % 2 === 0) {
        evens.push(all[i]);
      }
    }

    if (evens.length !== Math.ceil(count / 2)) {
      console.log(evens);
      throw new Error('oh no');
    }

    const [s, ns] = process.hrtime(start);
    console.log(`${'nativeArray'.padEnd(12)} took ${(s * 1000 * 1000 * 1000 + ns).toLocaleString().padStart(13)}ns to iterate ${count} times.`);
  }
}

bench();
```

```
iterEs5      took     1,682,832ns to iterate 1 times.
iterEs2015   took       782,684ns to iterate 1 times.
iterEs2018   took       573,525ns to iterate 1 times.
nativeGen    took        98,120ns to iterate 1 times.
nativeArray  took         7,051ns to iterate 1 times.
iterEs5      took    14,391,034ns to iterate 1000 times.
iterEs2015   took     6,066,771ns to iterate 1000 times.
iterEs2018   took     1,052,341ns to iterate 1000 times.
nativeGen    took       819,585ns to iterate 1000 times.
nativeArray  took        83,830ns to iterate 1000 times.
iterEs5      took 1,105,707,391ns to iterate 1000000 times.
iterEs2015   took 1,099,769,171ns to iterate 1000000 times.
iterEs2018   took   481,883,451ns to iterate 1000000 times.
nativeGen    took   380,105,838ns to iterate 1000000 times.
nativeArray  took    57,109,593ns to iterate 1000000 times.
```

but I digress. Looks like we should upgrade to 7.x and use ES2018! Thanks for all your help.

**Comment by conartist6** [comment]
No problem. It's useful to me to have those numbers as well. Async is going to cost something. You have to make all the promises, and promises never resolve synchronously so some of your time is lost just waiting for the next tick. As you can see that costs even more in <=es2015 where you're polyfilling async iteration. Arrays will still outperform sync iteration too, but then you're stuck with arrays and lots of major GCs.

**Comment by nomcopter** [comment]
Are you planning on forward porting `partition` to `7.x`?

**Comment by conartist6** [comment]
I removed partition because I felt it was unsound. Its behavior is particularly thorny for infinite iterables. You can get into an infinite loop if all of the elements fall on one side of the partition and your request the items on the other side.

**Comment by conartist6** [comment]
Just to report I'm working steadily on the full `v7.0.0` now. To my goal of not including anything unsound I'm reworking regex-based splitting. Right now I'm putting together `@iter-tools/regex` for evaluating regular expressions in a fully streaming fashion against iterables, and that should then unblock the rest of the string refactoring work.

**Comment by conartist6** [comment]
It's looking like it might be today or tomorrow!
