### ISSUE TITLE
Lazy replacement for `for...of` loop?

### ISSUE THREAD

**Issue by raineorshine** [iter-tools/iter-tools#370]
Being new to async iterables, I hope someone will indulge my newbie question. I come from an FP background and I find using a `for` loop sufficiently offensive. Does `iter-tools` have a function that lazily yields each item in an `AsyncIterable`? Or is there a simpler built-in way to do it? 

This is my best attempt so far:

```ts
async function *yieldAll(its: AsyncIterable<any>[]) {
  for (const it of its) yield* it
}

async function* foo(array) {
  ...
  yield* yieldAll(array.map(functionThatReturnsAsyncIterable))
}
```

I looked through the API and some of the source code but couldn't find anything.

**Comment by conartist6** [comment]
Look at the readme. Your question is best asked in our gitter channel. I'm
just as likely to respond there.

To your question, all of iter tools is pull-based/lazy. You don't need
async for that. Even a for loop is lazy, e.g. breaking out of the loop will
stop pulling values from an iterable source.

**Comment by raineorshine** [comment]
I guess I don't understand yet, but I will re-read the README and ask on the gitter channel. Thank you.

**Comment by conartist6** [comment]
I'm happy to help there. I get emails about gitter messages. Thanks for
closing the issue.
