### ISSUE TITLE
collate/asyncCollate incorrectly compare elements for ordering

### ISSUE THREAD

**Issue by chuckwondo** [iter-tools/iter-tools#433]
`collate` uses the `compare` function in the wrong "direction" for ordering (merging) elements. In `src/impls/$collate/[async-]collate.js`, the `[async]byComparison` function compares this way:

```javascript
if (!peekr.done && compare(candidate.value, peekr.value) < 0) {
  candidate = peekr;
}
```

That ends up assigning `candidate` the `peekr` with the _larger_ value rather than the one with the _smaller_ value.

I believe one possible fix is the following:

```javascript
if (!peekr.done && compare(peekr.value, candidate.value) < 0) {
  candidate = peekr;
}
```

The error is evidenced by this example, taken straight from `API.md`:

```javascript
collate((a, b) => b - a, [6, 5, 2, 1], [4, 3]); // Iterable[ 4, 3, 6, 5, 2, 1 ]
```

Notice that `b - a` is what _should_ work for _descending_ ordering, but it does not.  However, by changing the comparator to use `a - b` (intended for _ascending_ ordering), the correct _descending_ ordering is produced.

Further, the related tests pass for producing _ascending_ results because they use `b - a`, but should use `a - b` instead. In other words, for _ascending_ order, the comparator function must return a value less than 0 when `a < b`, which in the case of the tests means they should use `a - b`, not `b - a`.

**Comment by conartist6** [comment]
Oops! This is the sort of thing that slips through sometimes when nobody is reviewing my PRs...

**Comment by chuckwondo** [comment]
No worries. I was tearing my hair out trying to use `asyncCollate`, wondering why I was getting bizarre output, until I discovered the comparison problem. I submitted a fix.

Thanks for this excellent library!

**Comment by conartist6** [comment]
Thank you! I've put a lot of work in and I'm never really sure how many people are using it, so it's always fun to see a bit of evidence that people are finding it and want things I only ever imagined they might want : )
