### ISSUE TITLE
take during a period of time

### ISSUE THREAD

**Issue by GerkinDev** [iter-tools/iter-tools#459]
Hi,

I'm working with a never-ending async iterable, of which I'd like to extract values during a certain amount of time.

Example: Get all items yielded within the next 5s.

How can I achieve this simply ? I could wrap my iterable inside another one that completes on timeout, but I guess this could be a nice utility method directly available from within the package. Have I missed a doc page ?

Thank you

**Comment by conartist6** [comment]
```js
const start = Date.now();
asyncTakeWhile(() => Date.now() < start + 5000)
```

I do not think that pattern would satisfy the indications for creation of a new method (found in CONTRIBUTING.md). They are:

- The need for the implementation is very common.
- The implementation is complicated and/or bug-prone.
- The name very clearly implies the implementation.

I also think you should be a little careful with your language. What iter-tools will be able to do is make as many end-to-end serial requests as will fit in a 5-second window, but what you absolutely must remember to have a correct implementation is that that tells you nothing about what period of time the events were created in. Perhaps there will be a big garbage collection in your consumer code, and 5 seconds worth of requests from your client will only be enough to collect one second worth of values from your producer. Just from the way you describe the logic you want, it actually sounds to me like you'd prefer to be using RxJS and Observables, which is a push-based collection can be used to implement the exact logic you describe.

**Comment by GerkinDev** [comment]
Hi,

Indeed, in that very specific case, rxjs would be more appropriate. But I needed this in an isolated test where I expect my async iterable NOT to yield items after the ones I expect (which led me to #460). The full program is a CPU-heavy processing which needs to be pull-based; that's why I used iterables in the first place.

Why I thought it could be an additional method was because your suggested solution would complete the iterable after each yield, which could never happen or happen a very long time after the condition would actually return `true`.

Sorry for the unclear message. I don't really have the opportunity to use english appart from code-related stuff ^^"

Since I've managed to do my tests by other means, I close this issue.

**Comment by conartist6** [comment]
Ah don't worry your English is great! I just wanted to make sure you were thinking about how your code would work, and it seems that you are.

**Comment by GerkinDev** [comment]
Do you have any more feedback to give me about the edit I made to my comment while you were answering ?

> Why I thought it could be an additional method was because your suggested solution would complete the iterable after each yield, which could never happen or happen a very long time after the condition would actually return true.

**Comment by conartist6** [comment]
I'm not fully sure I understand your problem, but I do think that it's solvable, I'm just not sure which solution is right.

In general all methods in iter-tools do complete (call `return()` or exhaust) their iterables, which obviously is a problem if you have an infinite iterable that you need to keep using. The solution to that problem is [forkerate](https://github.com/iter-tools/iter-tools/blob/trunk/API.md#asyncforkerate)! Let me know if the docs are clear enough as to how that should work.
