### ISSUE TITLE
[Feature Request] sequentialEquals

### ISSUE THREAD

**Issue by hillin** [iter-tools/iter-tools#476]
Determines whether two iterables are equal by comparing the elements, optionally with a compare function.

I.e. a shorthand for

```typescript
execPipe(
  zip(a, b),
  every(([a, b]) => compare(a, b))
)

**Comment by conartist6** [comment]
Isn't that just `equal(a, b)`?

**Comment by hillin** [comment]
Wow good point, I've scanned the API docs for several times, why did I overlooked that one 🤔

**Comment by hillin** [comment]
@conartist6 It seems `equal` can only be used in its curried form, is this intentional?
Per the API docs:
```typescript
equal([1, 2, 3], [1, 2, 3], [1, 2, 3]); // true
```
But no, it actually returns a `(iterable: Wrappable<any>) => boolean`. This returns true:
```typescript
equal([1, 2, 3], [1, 2, 3])([1, 2, 3]); // true
```

**Comment by conartist6** [comment]
Huh. I don't know why that would be. I'm looking at the tests and that case is covered:

https://github.com/iter-tools/iter-tools/blob/8d8ba27ecb73b4b9bf24bab433ffd0ac16b82653/src/impls/%24equal/__tests__/equal.test.ts#L21-L29

**Comment by hillin** [comment]
Maybe that overload was not correctly typed?

**Comment by conartist6** [comment]
Oh yep, types again.

**Comment by hillin** [comment]
I already opened an issue complaining about the typings of `equal`, would be happy to open another one if needed ;-)

https://github.com/iter-tools/iter-tools/issues/477

**Comment by conartist6** [comment]
https://github.com/iter-tools/iter-tools/pull/478
