### ISSUE TITLE
Improve typings of the equal operator

### ISSUE THREAD

**Issue by hillin** [iter-tools/iter-tools#477]
Currently the typings of the `equal` use `any` everywhere. Preferably use generics instead.

https://github.com/iter-tools/iter-tools/blob/8d8ba27ecb73b4b9bf24bab433ffd0ac16b82653/src/impls/%24equal/%24equal.d.ts#L5-L16

**Comment by conartist6** [comment]
Why?

**Comment by conartist6** [comment]
Oh sorry I see what you're saying.

**Comment by hillin** [comment]
Maybe it's because [using `any` in typescript is generally considered a bad thing](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any)?

E.g. the compiler would not know if I'm writing the `same` function against the correct types.

**Comment by conartist6** [comment]
Updated the PR. I still can't use generics for the curried version cause TS isn't powerful enough but the non-curried version uses them now.

**Comment by conartist6** [comment]
Closed by #478. Released in `v7.3.3`.
