### ISSUE TITLE
Consider implementing `chunk` 

### ISSUE THREAD

**Issue by abozhilov** [iter-tools/iter-tools#485]
`chunk` is useful lodash function - https://lodash.com/docs/4.17.15#chunk and it could be implemented with iterators. 

I use the following implementation: 

```ts
export function* chunk<T>(
  iterable: Iterable<T>, 
  size: number
): Generator<T[]> {
  const chunkSize = Math.floor(size);

  if (chunkSize !== size || chunkSize < 1) {
    throw TypeError('Chunk size must be an integer greater or equal to 1.');
  }

  let res:T[] = [];
  let count = 0;

  for (const i of iterable) {
    res.push(i);

    if (++count % size === 0) {
      yield res;
      res = [];
    }
  }

  if (res.length) {
    yield res;
  }
}
```

**Comment by conartist6** [comment]
That's called [batch](https://github.com/iter-tools/iter-tools/blob/trunk/API.md#batch) and it's implemented with [spliterate](https://github.com/iter-tools/iter-tools/blob/trunk/API.md#spliterate)

**Comment by conartist6** [comment]
As a last note, `spliterate` chunks are iterables not arrays. If you need array chunks you would write:
```js
map(toArray, batch(size, iterable))
```
