### ISSUE TITLE
asyncBuffer has wrong signature in API.md

### ISSUE THREAD

**Issue by voda** [iter-tools/iter-tools#496]
https://github.com/iter-tools/iter-tools/blob/trunk/API.md#asyncbuffer

In the document it is `asyncBuffer(source, n)`, but according to the code should be `asyncBuffer(n, source)`.

**Comment by voda** [comment]
Fixed in https://github.com/iter-tools/iter-tools/pull/497

**Comment by conartist6** [comment]
I've completed the follow-up tasks so if you get to the API docs from the package's published README on [npm](https://www.npmjs.com/package/iter-tools) you should now also see correct docs for this method, and in the future we will be able to release those docs corrections without the need for a semver patch bump (as necessitated the release of `v7.5.3`).
