### ISSUE TITLE
Weird concat behaviour

### ISSUE THREAD

**Issue by anacierdem** [iter-tools/iter-tools#506]
The following code;

```js
await execPipe(
  range(0, 10),
  batch(2),
  concat,
  forEach((i) => console.log(arrayFrom(i)))
);
```

Results in this output:

```
[ 0, 1 ]
[ 2, 3 ]
[ 4, 5 ]
[ 6, 7 ]
[ 8, 9 ]
```

Looks like after concat the inner sources are still size 2 iterables. This is version `7.5.3`, what am I missing here?

Edit: I expect it to fail when trying to convert numbers into an array as they shouldn't be iterables.

**Comment by conartist6** [comment]
The batch docs say "Yields non-overlapping subsequences each containing size values from source."

With that being the case, do you still think anything is wrong? What were you hoping to do?

**Comment by conartist6** [comment]
Oh but maybe you're problem is that `concat` is varargs. I think you wanted:

```js
await execPipe(
  range(0, 10),
  batch(2),
  iterables => concat(...iterables), // or flatMap(i => i)
  forEach((i) => console.log(i))
);
```

**Comment by anacierdem** [comment]
Ah, that makes sense! That's what I wanted, you're right, thank you 😊
